config/routes.rb
Rails.application.routes.draw do
  # get '/articles' => 'articles#index'
  # get '/articles/new' => 'articles#new'
  # post '/articles' => 'articles#create', as: 'article_create'

  get '/users' => 'users#index', as: 'users'
  get '/users/new' => 'users#new', as: 'new_user'
  post '/users' => 'users#create', as: 'create_user'

  resources :articles do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  validates :name, presence: true,
                   uniqueness: true
  validates :body, presence: true,
                   length: { minimum: 5 }

  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.valid?
      @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  private

  def article_params
    params.require(:article).permit(:name, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_article

  def index
    @comments = @article.comments
  end

  def new
    @comment = @article.comments.build
  end

  def create
    @comment = @article.comments.build(comment_params)

    if @comment.save
      redirect_to article_comments_path
    else
      render :new
    end
  end

  private
  def get_article
    @article = Article.find(params[:article_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :article_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    # if user.save
      redirect_to users_path
    # else
    #   render :new
    # end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :middle_name, :last_name, :age, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Body</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article|  %>
      <tr>
        <td><%= article.id %></td>
        <td><%= article.name %></td>
        <td><%= article.body %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<%= link_to 'New article', new_article_path %>

app/views/articles/new.html.erb
<p>
  <%= form_with scope: :article, model: @article, local: true do |f| %>

  <div>
    <% if @article.errors.any? %>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    <% end %>

  </div>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name%>  
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_field :body%>  
  </div>

  <div>
    <%= f.submit %>
  </div>

  <% end %>
</p>

app/views/articles/show.html.erb
<h1>Name:</h1>
<%= @article.name %>

<h2>Body:</h2>
<%= @article.body %>

<div>
<%= link_to 'See all comments', article_comments_path(@article) %>
</div>

app/views/comments/index.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Body</th>
    <tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.id %></td>
        <td><%= comment.body %></td>
      </tr>

    <% end %>

  </tbody>

</table>

<%= link_to 'Add comment', new_article_comment_path(@article) %>

app/views/comments/new.html.erb
<%= form_with scope: :comment, model: [@article, @comment], local: true do |f| %>
  <p>
    <% if @comment.errors.any? %>
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </p>

  <p>
    <%= f.submit %>
  <p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Batch6Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_with scope: :user, url: create_user_path do |f| %>

  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div>
    <%= f.label :middle_name %>
    <%= f.text_field :middle_name %>
  </div>

  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div>
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>

  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>